import type { Post, PortfolioProject, Comment, NewsletterSubscriber, ContactMessage, DashboardStats, ViewsOverTime, TopPost, Profile } from "./types"

export const mockAuthor: Profile = {
  id: "mock-author-1",
  email: "brian@modantech.com",
  full_name: "Brian Muyinda",
  avatar_url: null,
  role: "admin",
  bio: "Full-stack developer and founder of MODARNTECH. Passionate about building digital solutions that transform businesses.",
  created_at: "2023-01-01T00:00:00Z",
}

export const mockPosts: Post[] = [
  {
    id: "1",
    title: "Building Scalable Web Applications with Next.js 16",
    slug: "building-scalable-web-apps-nextjs-16",
    description: "Learn how to leverage the latest Next.js features including Cache Components, React 19.2, and the new middleware system to build production-ready applications.",
    content: `## Introduction\n\nNext.js 16 brings groundbreaking features that make building scalable web applications easier than ever. In this comprehensive guide, we'll explore the key changes and how to leverage them.\n\n## Cache Components\n\nThe new \`use cache\` directive is a game-changer for performance. Instead of relying on complex caching strategies, you can now simply add the directive to any component or function.\n\n\`\`\`tsx\nexport async function ProductList() {\n  'use cache'\n  const products = await fetchProducts()\n  return <div>{products.map(p => <ProductCard key={p.id} product={p} />)}</div>\n}\n\`\`\`\n\n## React 19.2 Features\n\nReact 19.2 introduces several exciting features:\n\n- **useEffectEvent**: Extract non-reactive logic from Effects\n- **Activity**: Hide and restore UI and internal state\n- **Improved Suspense**: Better streaming and hydration\n\n## Turbopack is Stable\n\nTurbopack is now the default bundler, offering significantly faster build times compared to webpack. The migration is seamless for most projects.\n\n## Conclusion\n\nNext.js 16 represents a major leap forward in the React ecosystem. The new caching primitives, combined with React 19.2 features, make it the best framework for building modern web applications.`,
    feature_image: null,
    author_id: "mock-author-1",
    author: mockAuthor,
    status: "published",
    tags: ["Next.js", "React", "Web Development"],
    is_premium: false,
    read_time: 8,
    scheduled_at: null,
    seo_title: "Building Scalable Web Applications with Next.js 16 | MODARNTECH",
    seo_description: "A comprehensive guide to Next.js 16 features including Cache Components, React 19.2, and Turbopack.",
    created_at: "2026-02-10T10:00:00Z",
    updated_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "2",
    title: "The Complete Guide to Supabase Authentication",
    slug: "complete-guide-supabase-authentication",
    description: "A deep dive into implementing secure authentication with Supabase, including Row Level Security, social providers, and multi-factor authentication.",
    content: `## Why Supabase Auth?\n\nSupabase provides a complete authentication solution that works seamlessly with PostgreSQL and Row Level Security. Let's explore how to implement it properly.\n\n## Setting Up Auth\n\nFirst, configure your Supabase project with the appropriate auth providers. Supabase supports email/password, magic links, and 20+ social providers.\n\n## Row Level Security\n\nRLS is the backbone of Supabase security. Every table should have appropriate policies.\n\n\`\`\`sql\nCREATE POLICY "Users can read own data"\n  ON profiles FOR SELECT\n  USING (auth.uid() = id);\n\`\`\`\n\n## Best Practices\n\n1. Always enable RLS on all tables\n2. Use service role key only on the server\n3. Implement proper session refresh logic\n4. Add rate limiting to auth endpoints\n\n## Conclusion\n\nSupabase auth, combined with RLS, provides enterprise-grade security that's easy to implement and maintain.`,
    feature_image: null,
    author_id: "mock-author-1",
    author: mockAuthor,
    status: "published",
    tags: ["Supabase", "Authentication", "Security"],
    is_premium: false,
    read_time: 12,
    scheduled_at: null,
    seo_title: null,
    seo_description: null,
    created_at: "2026-02-05T08:00:00Z",
    updated_at: "2026-02-05T08:00:00Z",
  },
  {
    id: "3",
    title: "Mobile App Development with React Native in 2026",
    slug: "mobile-app-development-react-native-2026",
    description: "Discover the latest React Native features and best practices for building production-quality mobile applications in 2026.",
    content: `## The State of React Native\n\nReact Native continues to evolve rapidly. In 2026, the New Architecture is now stable and widely adopted, bringing significant performance improvements.\n\n## Key Features\n\n### Fabric Renderer\nThe new Fabric renderer provides better performance with synchronous layout and concurrent features support.\n\n### TurboModules\nTurboModules enable lazy loading of native modules, reducing startup time significantly.\n\n## Best Practices\n\n- Use TypeScript for type safety\n- Implement proper navigation with React Navigation 7\n- Optimize images and assets\n- Use Reanimated 3 for smooth animations\n\n## Conclusion\n\nReact Native remains the top choice for cross-platform mobile development, offering near-native performance with a single codebase.`,
    feature_image: null,
    author_id: "mock-author-1",
    author: mockAuthor,
    status: "published",
    tags: ["React Native", "Mobile", "Cross-Platform"],
    is_premium: false,
    read_time: 6,
    scheduled_at: null,
    seo_title: null,
    seo_description: null,
    created_at: "2026-01-28T14:00:00Z",
    updated_at: "2026-01-28T14:00:00Z",
  },
  {
    id: "4",
    title: "Data Visualization Best Practices for Business Dashboards",
    slug: "data-visualization-best-practices-dashboards",
    description: "Learn how to create effective data visualizations that drive decision-making with modern charting libraries and design principles.",
    content: `## Why Data Visualization Matters\n\nEffective data visualization transforms complex datasets into actionable insights. In this guide, we cover the principles and tools for building impactful business dashboards.\n\n## Choosing the Right Chart Type\n\n- **Line charts**: Trends over time\n- **Bar charts**: Comparisons between categories\n- **Pie charts**: Part-to-whole relationships (use sparingly)\n- **Scatter plots**: Correlations between variables\n\n## Design Principles\n\n1. Keep it simple - remove unnecessary decorations\n2. Use consistent color coding\n3. Provide clear labels and legends\n4. Make it interactive where possible\n\n## Modern Tools\n\nRecharts, D3.js, and Chart.js are the most popular libraries for web-based data visualization. Each has its strengths.\n\n## Conclusion\n\nGood data visualization is both an art and a science. Focus on clarity and actionability.`,
    feature_image: null,
    author_id: "mock-author-1",
    author: mockAuthor,
    status: "published",
    tags: ["Data Analysis", "Visualization", "Business"],
    is_premium: true,
    read_time: 10,
    scheduled_at: null,
    seo_title: null,
    seo_description: null,
    created_at: "2026-01-20T09:00:00Z",
    updated_at: "2026-01-20T09:00:00Z",
  },
  {
    id: "5",
    title: "SEO Strategies That Actually Work in 2026",
    slug: "seo-strategies-that-work-2026",
    description: "Cut through the noise with proven SEO strategies focused on Core Web Vitals, AI-generated content optimization, and semantic search.",
    content: `## SEO in 2026\n\nSEO has evolved significantly. Google's algorithms now prioritize user experience, content quality, and semantic understanding over keyword stuffing.\n\n## Core Web Vitals\n\nPerformance matters more than ever. Focus on LCP, FID, and CLS metrics to improve rankings.\n\n## Content Strategy\n\n- Write comprehensive, authoritative content\n- Focus on E-E-A-T principles\n- Optimize for featured snippets\n- Use structured data markup\n\n## Technical SEO\n\n1. Ensure fast page loads\n2. Implement proper meta tags\n3. Build a clean site architecture\n4. Optimize for mobile-first indexing\n\n## Conclusion\n\nFocus on providing genuine value to users, and the rankings will follow.`,
    feature_image: null,
    author_id: "mock-author-1",
    author: mockAuthor,
    status: "draft",
    tags: ["SEO", "Marketing", "Strategy"],
    is_premium: false,
    read_time: 7,
    scheduled_at: null,
    seo_title: null,
    seo_description: null,
    created_at: "2026-01-15T11:00:00Z",
    updated_at: "2026-01-15T11:00:00Z",
  },
]

export const mockProjects: PortfolioProject[] = [
  {
    id: "1",
    title: "E-Commerce Platform",
    description: "A full-featured e-commerce platform built with Next.js, Stripe integration, and real-time inventory management.",
    image_url: null,
    tech_stack: ["Next.js", "TypeScript", "Stripe", "Supabase", "Tailwind CSS"],
    category: "Web Development",
    live_url: "https://example-ecommerce.com",
    github_url: "https://github.com/modantech/ecommerce",
    case_study: "Increased client revenue by 40% through optimized checkout flow and mobile-first design. The platform handles 10,000+ daily transactions with 99.9% uptime.",
    featured: true,
    sort_order: 1,
    created_at: "2025-11-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Health Tracking Mobile App",
    description: "Cross-platform mobile application for health tracking with AI-powered insights and wearable device integration.",
    image_url: null,
    tech_stack: ["React Native", "TypeScript", "Python", "TensorFlow", "Firebase"],
    category: "Mobile Development",
    live_url: null,
    github_url: "https://github.com/modantech/healthapp",
    case_study: "Served 50,000+ users with real-time health monitoring. The AI model provides 92% accuracy in predicting health trends.",
    featured: true,
    sort_order: 2,
    created_at: "2025-09-15T00:00:00Z",
  },
  {
    id: "3",
    title: "Business Analytics Dashboard",
    description: "Real-time analytics dashboard with custom visualization components, automated reporting, and data pipeline management.",
    image_url: null,
    tech_stack: ["React", "D3.js", "Python", "PostgreSQL", "Docker"],
    category: "Data Analysis",
    live_url: "https://example-analytics.com",
    github_url: null,
    case_study: "Reduced report generation time from 4 hours to 15 minutes. Dashboard processes 2M+ data points in real-time.",
    featured: true,
    sort_order: 3,
    created_at: "2025-07-20T00:00:00Z",
  },
  {
    id: "4",
    title: "Restaurant Booking System",
    description: "Online reservation system with table management, menu builder, and customer notifications.",
    image_url: null,
    tech_stack: ["Next.js", "Supabase", "Twilio", "Tailwind CSS"],
    category: "Web Development",
    live_url: "https://example-booking.com",
    github_url: null,
    case_study: null,
    featured: false,
    sort_order: 4,
    created_at: "2025-05-10T00:00:00Z",
  },
  {
    id: "5",
    title: "Logistics Tracking App",
    description: "Real-time fleet tracking and logistics management mobile application with route optimization.",
    image_url: null,
    tech_stack: ["Flutter", "Google Maps API", "Node.js", "MongoDB"],
    category: "Mobile Development",
    live_url: null,
    github_url: "https://github.com/modantech/logistics",
    case_study: null,
    featured: false,
    sort_order: 5,
    created_at: "2025-03-05T00:00:00Z",
  },
  {
    id: "6",
    title: "Marketing Campaign Analyzer",
    description: "Data analysis tool that evaluates marketing campaign performance across multiple channels with predictive ROI modeling.",
    image_url: null,
    tech_stack: ["Python", "Pandas", "React", "Chart.js", "AWS"],
    category: "Data Analysis",
    live_url: null,
    github_url: null,
    case_study: null,
    featured: false,
    sort_order: 6,
    created_at: "2025-01-18T00:00:00Z",
  },
]

export const mockComments: Comment[] = [
  {
    id: "1",
    post_id: "1",
    author_name: "Sarah K.",
    author_email: "sarah@example.com",
    content: "Great article! The Cache Components section was really helpful. Looking forward to migrating our project.",
    approved: true,
    created_at: "2026-02-11T15:30:00Z",
  },
  {
    id: "2",
    post_id: "1",
    author_name: "James M.",
    author_email: "james@example.com",
    content: "Can you elaborate on the Turbopack migration? We had some issues with custom webpack plugins.",
    approved: true,
    created_at: "2026-02-12T09:00:00Z",
  },
  {
    id: "3",
    post_id: "2",
    author_name: "Alice W.",
    author_email: "alice@example.com",
    content: "The RLS section is exactly what I needed. Thanks for the clear examples!",
    approved: true,
    created_at: "2026-02-06T18:45:00Z",
  },
  {
    id: "4",
    post_id: "3",
    author_name: "Tom R.",
    author_email: "tom@example.com",
    content: "Would love to see a follow-up on React Native performance optimization.",
    approved: false,
    created_at: "2026-02-14T12:00:00Z",
  },
]

export const mockSubscribers: NewsletterSubscriber[] = [
  { id: "1", email: "subscriber1@example.com", confirmed: true, created_at: "2026-01-01T00:00:00Z" },
  { id: "2", email: "subscriber2@example.com", confirmed: true, created_at: "2026-01-05T00:00:00Z" },
  { id: "3", email: "subscriber3@example.com", confirmed: true, created_at: "2026-01-10T00:00:00Z" },
  { id: "4", email: "subscriber4@example.com", confirmed: false, created_at: "2026-01-15T00:00:00Z" },
  { id: "5", email: "subscriber5@example.com", confirmed: true, created_at: "2026-01-20T00:00:00Z" },
  { id: "6", email: "subscriber6@example.com", confirmed: true, created_at: "2026-01-25T00:00:00Z" },
  { id: "7", email: "subscriber7@example.com", confirmed: true, created_at: "2026-02-01T00:00:00Z" },
  { id: "8", email: "subscriber8@example.com", confirmed: true, created_at: "2026-02-05T00:00:00Z" },
]

export const mockContactMessages: ContactMessage[] = [
  {
    id: "1", name: "John D.", email: "john@example.com", subject: "Project Inquiry",
    message: "Hi, I'm interested in building an e-commerce platform for my business. Can we schedule a call?",
    read: true, created_at: "2026-02-10T14:00:00Z",
  },
  {
    id: "2", name: "Maria L.", email: "maria@example.com", subject: "Mobile App Quote",
    message: "We need a mobile app for our restaurant chain. Looking for both iOS and Android support.",
    read: false, created_at: "2026-02-14T09:30:00Z",
  },
  {
    id: "3", name: "David K.", email: "david@example.com", subject: "Partnership Opportunity",
    message: "Our agency is looking for a development partner for upcoming projects. Would love to discuss.",
    read: false, created_at: "2026-02-15T16:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalPosts: 5,
  totalViews: 12480,
  totalSubscribers: 8,
  totalMessages: 3,
}

export const mockViewsOverTime: ViewsOverTime[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date()
  date.setDate(date.getDate() - (29 - i))
  return {
    date: date.toISOString().split("T")[0],
    views: Math.floor(Math.random() * 500) + 100,
  }
})

export const mockTopPosts: TopPost[] = [
  { id: "1", title: "Building Scalable Web Applications with Next.js 16", slug: "building-scalable-web-apps-nextjs-16", views: 4520 },
  { id: "2", title: "The Complete Guide to Supabase Authentication", slug: "complete-guide-supabase-authentication", views: 3200 },
  { id: "3", title: "Mobile App Development with React Native in 2026", slug: "mobile-app-development-react-native-2026", views: 2800 },
  { id: "4", title: "Data Visualization Best Practices for Business Dashboards", slug: "data-visualization-best-practices-dashboards", views: 1200 },
  { id: "5", title: "SEO Strategies That Actually Work in 2026", slug: "seo-strategies-that-work-2026", views: 760 },
]
